### PR TITLE
merge jarvisc1 changes in support of reproduce-ability of covidm_reports

### PR DESCRIPTION
**Pull request by pearsonca**
In the run up to publishing the covidm_reports work, I'd like to eliminate dependency on custom socialmixr.

Putting this in a placeholder, and I'll help with any necessary adjustments to get it properly incorporated.

### CODE REVIEW

**Comment by sbfnk** [comment]
Is this not what was merged in https://github.com/sbfnk/socialmixr/commit/efa346e600c22396e7f5164a475ae631d96b4df4?

**Comment by pearsonca** [comment]
Hmm, not sure? File changes still show deltas, which seems odd if the changes are already in there.

**Comment by sbfnk** [comment]
I think it's showing file changes because `sbfnk:master` hasn't been merged into `jarvisc1:master`.

**Comment by sbfnk** [comment]
Closing for now. Please re-open if you think it's still relevant.

**Pull request closed without merging**
